package com.habibi.modern.enums;

public enum ErrorCode {
    TIME_OUT_OR_UNREACHABLE_CORE,
    CORE_THROWS_500,
    INSUFFICIENT_FUNDS,
    WITHDRAW_OF_ROLLBACK_NOT_FOUND,
    ROLLBACKING_THE_ROLLBACKED_WITHDRAW
}