package com.habibi.modern.enums;

public enum ErrorCode {
    CORE_IS_UNREACHABLE,
    CORE_THROWS_INTERNAL_SERVER_ERROR,
    INSUFFICIENT_FUNDS,
    WITHDRAW_OF_ROLLBACK_NOT_FOUND,
    ROLLBACKING_THE_ROLLBACKED_WITHDRAW,
    BAD_REQUEST_EXCEPTION,
    SIGNUP_INSUFFICIENT_FUNDS,
    DUPLICATION_NATIONAL_CODE_REGISTRATION,
    DUPLICATION_USERNAME_REGISTRATION
}