package com.habibi.modern.enums;

public enum RequestStatus {
    CREATED,
    SIGNUP_DONE,
    CORE_IS_UNREACHABLE,
    RESOLVED_CONFLICT_BY_ROLLBACKING_ITS_WITHDRAW_TRANSACTION,
    RESOLVED_CONFLICT_CONTAINS_TRANSACTION_HAS_BAD_REQUEST_ERROR
}